'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Check,Plus,Search} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {mergeSelection} from '@/lib/media-selection';
import {api,post,type Media} from '@/lib/brief-api';

export function MediaSettings({country,revision,onChanged}:{country:string;revision:number;onChanged:()=>void}){
 const [media,setMedia]=useState<Media|null>(null),[selected,setSelected]=useState<Set<string>>(new Set()),[search,setSearch]=useState(''),[website,setWebsite]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const edits=useRef(new Map<string,boolean>()),activeCountry=useRef(country),generation=useRef(0);
 activeCountry.current=country;
 useEffect(()=>{edits.current.clear();setMedia(null);setSelected(new Set());setMessage('')},[country]);
 useEffect(()=>{let active=true;const version=++generation.current;if(country)api<Media>('media?country='+country).then(m=>{if(active&&version===generation.current){setMedia(m);setSelected(mergeSelection(m.outlets,edits.current))}}).catch(e=>{if(active)setMessage(e.message)});return()=>{active=false}},[country,revision]);
 function choose(next:Set<string>){for(const o of media?.outlets||[])edits.current.set(o.id,next.has(o.id));setSelected(next)}
 async function save(){setBusy(true);setMessage('');++generation.current;try{const m=await api<Media>('media/select',post({country,ids:[...selected]}));if(activeCountry.current!==country)return;edits.current.clear();setMedia(m);setSelected(mergeSelection(m.outlets,edits.current));setMessage('Media selection saved. Your briefing is refreshing.');onChanged()}catch(e){if(activeCountry.current===country)setMessage(e instanceof Error?e.message:'Could not save sources.')}finally{setBusy(false)}}
 async function add(){if(!website.trim())return;setBusy(true);setMessage('');++generation.current;try{const m=await api<Media>('media/add',post({country,website,name}));if(activeCountry.current!==country)return;setMedia(m);setSelected(mergeSelection(m.outlets,edits.current));setWebsite('');setName('');setMessage('Website added. Looking for its indexed reporting.');onChanged()}catch(e){if(activeCountry.current===country)setMessage(e instanceof Error?e.message:'Could not add website.')}finally{setBusy(false)}}
 const visible=media?.outlets.filter(o=>(o.name+' '+o.domain+' '+JSON.stringify(o.catalog?.entries||[])).toLowerCase().includes(search.toLowerCase()))||[];
 const dirty=!!media&&(selected.size!==media.selected_count||media.outlets.some(o=>!!o.selected!==selected.has(o.id)));
 return <section className="settings-card source-settings"><div className="section-heading"><h2>Your media in {media?.country_name||'this country'}</h2><span>{selected.size} selected · {media?.outlets.length||0} available</span></div><p className="settings-intro">{media?.ranking} Up to 50 supported outlets are selected for a new country. Uncheck any outlet or add more. A source listing does not guarantee current articles.</p>
 <div className="media-toolbar"><label className="media-search"><Search size={16}/><input aria-label="Search media outlets" placeholder="Find a media outlet…" value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="secondary-button" disabled={busy} onClick={()=>choose(new Set(media?.outlets.filter(o=>o.catalog?.supported!==false).slice(0,50).map(o=>o.id)||[]))}>Select top 50</button><button className="text-link" disabled={busy} onClick={()=>choose(new Set())}>Clear selection</button></div>
 {!media?<p className="small-note">Loading your source library…</p>:!media.initialized?<p className="small-note">Your country’s source discovery is running. The library appears after the first briefing loads.</p>:media.outlets.length<50?<p className="small-note">{media.outlets.length} outlets discovered so far. All available outlets were selected initially; you can add a website below.</p>:null}
 <div className="media-list">{visible.map(o=><label key={o.id} className="media-outlet"><Checkbox disabled={busy||o.catalog?.supported===false} checked={selected.has(o.id)} onCheckedChange={checked=>{const n=new Set(selected);if(checked)n.add(o.id);else n.delete(o.id);edits.current.set(o.id,!!checked);setSelected(n)}} aria-label={`Include ${o.name}`}/><span><strong>{o.name}</strong><small>{o.domain}{o.major?' · Major outlet':''}{o.custom?' · Added by you':''}</small>{o.catalog&&<><small className="catalog-score">Priority {o.catalog.priority_score}/100 · {o.catalog.priority_tier.replaceAll('_',' ')} · Catalogue {o.catalog.as_of}</small>{o.catalog.entries.map((entry,i)=><small key={i}>{[entry.category.replaceAll('_',' '),entry.primary_language||entry.language,entry.region,entry.type,entry.format,entry.focus].filter(Boolean).join(' · ')}</small>)}{!o.catalog.supported&&<small>YouTube channel · external link only; video ingestion is not supported</small>}</>}</span><a href={o.url} aria-label={`Visit ${o.name}`} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}><ArrowUpRight size={15}/></a></label>)}</div>
 <div className="media-actions"><button className="primary-button" disabled={busy||!dirty} onClick={save}><Check size={16}/>Apply media selection</button><span>{dirty?'Unsaved changes':`${media?.selected_count||0} outlets in your briefing`}</span></div>
 <form className="add-media" onSubmit={e=>{e.preventDefault();add()}}><h3>Add a media website</h3><p>We’ll look for its reporting in the news index. Some websites may have no indexed coverage.</p><div><input aria-label="Media website" placeholder="Website, e.g. thehindu.com" value={website} onChange={e=>setWebsite(e.target.value)} maxLength={250}/><input aria-label="Media name" placeholder="Display name (optional)" value={name} onChange={e=>setName(e.target.value)} maxLength={100}/><button className="secondary-button" disabled={busy||!website.trim()}><Plus size={16}/>Add website</button></div></form>
 {message&&<p className="settings-feedback" role="status">{message}</p>}</section>;
}
