'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUp,ArrowUpRight,Bookmark,Check,ChevronRight,Clock3,Compass,Globe2,KeyRound,Loader2,MapPin,Moon,Newspaper,RefreshCw,Search,Settings2,ShieldCheck,Sparkles,Sun,X} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Skeleton} from '@/components/ui/skeleton';
import {CountryPicker} from './country-picker';
import {MediaSettings} from './media-settings';
import {api,post,ago,type Story,type Brief,type Status,type Country} from '@/lib/brief-api';
function shortText(value:string){const words=value.trim().split(/\s+/);return words.length<=60?value:words.slice(0,60).join(' ')+'…'}
function StoryImage({url,title}:{url?:string;title:string}){const [failed,setFailed]=useState(false);if(!url||failed)return null;return <div className="short-image"><img src={url} alt={title} loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/></div>}
const topics=['All','World','Technology','Business','Science','Climate'];
function Filter({label,value,options,onChange}:{label:string;value:string;options:{value:string;label:string}[];onChange:(value:string)=>void}){return <Select value={value} onValueChange={v=>{if(v)onChange(v)}}><SelectTrigger className="filter-select" aria-label={label}><SelectValue>{options.find(o=>o.value===value)?.label}</SelectValue></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
function Badge({story,onClick}:{story:Story;onClick:()=>void}){const v=story.verification;return <button className="evidence-badge outlet-coverage" onClick={onClick}><Newspaper size={13}/>{v.major_count} major {v.major_count===1?'outlet':'outlets'} · {v.total_count} total<ChevronRight size={12}/></button>}

export default function Home(){
 const [tab,setTab]=useState('today'),[brief,setBrief]=useState<Brief|null>(null),[status,setStatus]=useState<Status|null>(null),[saved,setSaved]=useState<Story[]>([]),[loading,setLoading]=useState(false),[booting,setBooting]=useState(true),[error,setError]=useState('');
 const [topic,setTopic]=useState('All'),[period,setPeriod]=useState('day'),[country,setCountry]=useState(''),[countries,setCountries]=useState<Country[]>([]),[onboarding,setOnboarding]=useState(false),[chosen,setChosen]=useState(''),[countryBusy,setCountryBusy]=useState(false);
 const [coverageFilter,setCoverageFilter]=useState('all'),[query,setQuery]=useState(''),[activeQuery,setActiveQuery]=useState(''),[selected,setSelected]=useState<Story|null>(null),[dark,setDark]=useState(false),[toast,setToast]=useState(''),[date,setDate]=useState('Your daily edition'),[mediaRevision,setMediaRevision]=useState(0);
 const [articleCount,setArticleCount]=useState(50);const countRef=useRef(50);
 const [groqKey,setGroqKey]=useState(''),[keyBusy,setKeyBusy]=useState(false),[keyMessage,setKeyMessage]=useState('');
 const controller=useRef<AbortController|null>(null),requestId=useRef(0),countryChangeId=useRef(0),countryRef=useRef(''),filtersRef=useRef({topic:'All',period:'day'}),intentRef=useRef<Record<string,unknown>|null>(null);
 const countryName=countries.find(c=>c.code===country)?.name||'your country';
 async function refreshStatus(code=countryRef.current){try{setStatus(await api<Status>('status'+(code?'?country='+code:'')))}catch{}}
 function cancel(){controller.current?.abort();requestId.current++;setLoading(false)}
 async function load(q='',options:{country?:string;topic?:string;period?:string;refresh?:boolean;followup?:boolean}={}){
  const code=options.country||countryRef.current;if(!code){setOnboarding(true);return}
  controller.current?.abort();const ctrl=new AbortController();controller.current=ctrl;const id=++requestId.current;
  setLoading(true);setError('');setActiveQuery(q);setBrief(null);
  const filters={...filtersRef.current,...options};
  try{
   const result=await api<Brief>('query',{...post({query:q,count:countRef.current,country:code,topic:filters.topic,period:filters.period,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,refresh:!!options.refresh,previous:options.followup?intentRef.current:null}),signal:ctrl.signal});
   if(id!==requestId.current)return;
   setBrief(result);intentRef.current=result.intent;setTopic(String(result.intent.topic));setPeriod(String(result.intent.period));filtersRef.current={topic:String(result.intent.topic),period:String(result.intent.period)};setMediaRevision(r=>r+1);refreshStatus(code);
  }catch(e){if(id===requestId.current&&!ctrl.signal.aborted)setError(e instanceof Error?e.message:'Unable to load news.')}
  finally{if(id===requestId.current)setLoading(false)}
 }
 async function boot(){
  setBooting(true);setError('');
  try{const [cs,pref]=await Promise.all([api<Country[]>('countries'),api<{country:string|null;article_count:number}>('preferences')]);setCountries(cs);const savedCount=Number(localStorage.getItem('worldbrief-article-count'));const n=Number.isInteger(savedCount)&&savedCount>=1&&savedCount<=100?savedCount:pref.article_count;countRef.current=n;setArticleCount(n);if(pref.country){countryRef.current=pref.country;setCountry(pref.country);load('',{country:pref.country})}else setOnboarding(true);refreshStatus(pref.country||'');api<Story[]>('saved').then(setSaved).catch(()=>{})}
  catch(e){setError(e instanceof Error?e.message:'Cannot connect to the assistant.')}
  finally{setBooting(false)}
 }
 useEffect(()=>{
  const pref=localStorage.getItem('worldbrief-theme');const isDark=pref==='dark'||(!pref&&window.matchMedia('(prefers-color-scheme: dark)').matches);setDark(isDark);document.documentElement.classList.toggle('dark',isDark);setDate(new Intl.DateTimeFormat('en',{weekday:'long',month:'long',day:'numeric'}).format(new Date()));boot();
  const timer=setInterval(()=>refreshStatus(),30000);return()=>{clearInterval(timer);controller.current?.abort()};
 },[]);
 useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(timer)}},[toast]);
 function theme(){const d=!dark;setDark(d);document.documentElement.classList.toggle('dark',d);localStorage.setItem('worldbrief-theme',d?'dark':'light')}
 async function changeCountry(code:string){
  const id=++countryChangeId.current;cancel();setCountryBusy(true);setError('');setBrief(null);setQuery('');setActiveQuery('');intentRef.current=null;
  try{await api('preferences',post({country:code}));if(id!==countryChangeId.current)return;countryRef.current=code;setCountry(code);setOnboarding(false);setMediaRevision(r=>r+1);load('',{country:code,refresh:true});refreshStatus(code)}
  catch(e){if(id===countryChangeId.current)setError(e instanceof Error?e.message:'Country could not be saved.')}
  finally{if(id===countryChangeId.current)setCountryBusy(false)}
 }
 async function bookmark(s:Story){try{await api(`saved/${s.id}`,{method:s.saved?'DELETE':'POST'});setBrief(b=>b?{...b,stories:b.stories.map(x=>x.id===s.id?{...x,saved:!x.saved}:x)}:b);setSelected(x=>x?.id===s.id?{...x,saved:!x.saved}:x);setSaved(await api<Story[]>('saved'));setToast(s.saved?'Removed from saved stories':'Story saved for later')}catch(e){setToast(e instanceof Error?e.message:'Could not save story')}}
 function changeCount(value:string){const n=Number(value);if(!Number.isInteger(n)||n<1||n>100)return;countRef.current=n;setArticleCount(n);localStorage.setItem('worldbrief-article-count',String(n));intentRef.current=null;load('',{refresh:false})}
 function ask(q:string){if(!q.trim())return;setTab('today');setQuery('');load(q,{followup:!!activeQuery})}
 function changeFilter(key:'topic'|'period',value:string){filtersRef.current={...filtersRef.current,[key]:value};if(key==='topic')setTopic(value);else setPeriod(value);load('',{[key]:value,refresh:true})}
 async function saveKey(){setKeyBusy(true);setKeyMessage('');try{const r=await api<{saved:boolean;status:string}>('settings/groq',post({key:groqKey}));setGroqKey('');setKeyMessage(r.status==='ready'?'Key saved. Groq is connected. No restart needed.':`Key saved, but the connection check returned: ${r.status.replaceAll('_',' ')}.`);refreshStatus()}catch(e){setKeyMessage(e instanceof Error?e.message:'Could not save key.')}finally{setKeyBusy(false)}}
 async function testKey(){setKeyBusy(true);try{const r=await api<{status:string}>('settings/groq/test',post({}));setKeyMessage(r.status==='ready'?'Groq is connected.':`Connection: ${r.status.replaceAll('_',' ')}.`);refreshStatus()}catch(e){setKeyMessage(e instanceof Error?e.message:'Connection failed.')}finally{setKeyBusy(false)}}
 const stories=(tab==='saved'?saved:brief?.stories||[]).filter(s=>coverageFilter!=='multiple'||s.verification.major_count>=2);
 function card(s:Story){const summary=shortText(s.summary);return <article className="story-card short-card" key={s.id}>
  <StoryImage key={s.image_url||s.id} url={s.image_url} title={s.title}/><div className="short-content">
  <div className="story-top"><span className={`topic-label topic-${s.topic.toLowerCase()}`}>{s.topic}{s.local_priority?<span className="local-priority"> · {s.country_name||countryName}</span>:null}</span><button className={`icon-button save-button ${s.saved?'is-saved':''}`} aria-label={s.saved?'Unsave story':'Save story'} onClick={()=>bookmark(s)}><Bookmark size={18} fill={s.saved?'currentColor':'none'}/></button></div>
  <button className="story-title-button" onClick={()=>setSelected(s)}><h2>{s.title}</h2></button>
  <div className="short-byline"><span>{s.sources[0]?.publisher}</span><span>·</span><time dateTime={new Date(s.published_at*1000).toISOString()}>{ago(s.published_at)}</time></div>
  {s.summary_kind==='headline'?<p className="headline-fallback">Headline only. Open the reporting for the full story.</p>:<p className="story-summary">{summary}</p>}
  <div className="short-caption">{s.summary_kind==='groq_summary'?'AI brief':s.summary_kind==='headline'?'Summary unavailable':'Publisher excerpt'}{s.summary_kind!=='headline'&&` · ${summary.trim().split(/\s+/).length} words`}</div>
  <div className="story-bottom"><Badge story={s} onClick={()=>setSelected(s)}/>{s.sources[0]&&<a className="article-link" href={s.sources[0].url} target="_blank" rel="noreferrer">{s.sources[0].link_kind==='original'?'Read full article':'Read via news index'}<ArrowUpRight size={15}/></a>}</div>
  </div></article>}
 const newsSurface=<><div className="page-heading"><div><p className="eyebrow">{date}</p><h1>{tab==='saved'?'Saved for later.':tab==='explore'?'Explore the news.':country?`${countryName}, in brief.`:'Your news, in brief.'}</h1><p className="heading-description">{tab==='saved'?'Your reading list, right where you left it.':'The essentials, in up to 60 words. Read further when a story interests you.'}</p></div><div className="heading-actions"><CountryPicker countries={countries} value={country} onChange={changeCountry}/><button className="refresh-button" onClick={()=>load(activeQuery,{refresh:true})} disabled={!country||countryBusy}><RefreshCw size={16} className={loading?'spin':''}/><span>Refresh</span></button></div></div>
 <div className="workspace-grid short-feed"><section className="news-column" aria-label="News stories">
 {tab!=='saved'&&<><form onSubmit={e=>{e.preventDefault();ask(query)}} className="feed-search"><Search size={19}/><label className="sr-only" htmlFor="news-query">Ask about the news</label><input id="news-query" placeholder={`Ask about ${countryName}, or search a topic…`} value={query} onChange={e=>setQuery(e.target.value)} maxLength={1000}/><button type="submit" aria-label="Send question" disabled={!query.trim()||!country}><ArrowUp size={18}/></button></form><div className="topic-filters" aria-label="Topics">{topics.map(t=><button key={t} className={topic===t?'active':''} aria-pressed={topic===t} onClick={()=>changeFilter('topic',t)}>{t}</button>)}</div><div className="filters-row"><label className="article-count">Articles<input aria-label="Number of articles" type="number" min={1} max={100} defaultValue={articleCount} key={articleCount} title="1–100 articles. Press Enter or leave the field to apply." onBlur={e=>{if(!e.target.value||!e.target.validity.valid){e.target.value=String(articleCount);return}if(Number(e.target.value)!==articleCount)changeCount(e.target.value)}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur()}}/></label><Filter label="Time range" value={period} options={[{value:'day',label:'Last 24 hours'},{value:'today',label:'Today'},{value:'yesterday',label:'Yesterday'},{value:'week',label:'Past week'}]} onChange={v=>changeFilter('period',v)}/><Filter label="Outlet coverage" value={coverageFilter} options={[{value:'all',label:'All coverage'},{value:'multiple',label:'2+ major outlets'}]} onChange={setCoverageFilter}/><button className="media-shortcut" onClick={()=>setTab('settings')}><Settings2 size={14}/>{brief?.selected_sources??'Your'} media outlets<ChevronRight size={13}/></button></div></>}
 <div className="section-heading"><h2>{activeQuery&&tab!=='saved'?'Your results':tab==='saved'?'Reading list':'Top stories'} <span>{stories.length}</span></h2>{brief&&tab!=='saved'&&<span className="freshness"><span className={`status-dot ${brief.stale?'amber':''}`}/>{brief.stale?'Saved coverage':brief.cache==='fresh'?'Updated':'Cached answer'} · {ago(brief.source_updated_at)}</span>}</div>
 {activeQuery&&tab!=='saved'&&<div className="query-result-label"><Search size={16}/><span>{activeQuery}</span><button aria-label="Clear question" onClick={()=>load()}><X size={16}/></button></div>}
 {error&&<div className="error-panel" role="alert"><p>{error}</p><button onClick={()=>countries.length?load(activeQuery):boot()}>Try again</button></div>}
 {(loading||booting)&&tab!=='saved'?<div className="loading-stories" role="status"><div className="loading-copy"><Loader2 className="spin" size={17}/><span>{booting?'Connecting to your assistant…':`Preparing news for ${countryName}…`}</span>{loading&&<button className="text-link cancel-request" onClick={cancel}>Cancel</button>}</div><p className="small-note">You can send another question while this loads. It will replace the current request.</p>{[0,1,2].map(i=><div className="loading-card" key={i}><Skeleton className="h-4 w-24"/><Skeleton className="h-8 w-4/5"/><Skeleton className="h-4 w-full"/></div>)}</div>:stories.length?<div className="stories-grid">{stories.map(card)}</div>:<div className="empty-state"><Newspaper size={34}/><h3>{tab==='saved'?'A little reading for later.':!country?'Start with your country.':brief?.selected_sources===0?'No media outlets selected.':'No stories in this view yet.'}</h3><p>{tab==='saved'?'Tap the bookmark on any story to keep it here.':!country?'Choose a country to build your personal edition.':brief?.selected_sources===0?'Choose media outlets in Settings to receive stories. You can start with the ranked top 50.':'Try a wider time range or include more media outlets in Settings.'}</p>{tab!=='saved'&&<button className="primary-button" onClick={()=>{if(!country){setOnboarding(true);return}if(brief?.selected_sources===0){setTab('settings');return}setCoverageFilter('all');filtersRef.current={topic:'All',period:'week'};setTopic('All');setPeriod('week');load('',{topic:'All',period:'week',refresh:true})}}>{!country?'Choose country':brief?.selected_sources===0?'Choose media outlets':'Show this week’s news'}</button>}</div>}
 {brief&&tab!=='saved'&&<p className="small-note">Showing {brief.stories.length} of up to {brief.requested_count} requested stories before coverage filtering. Availability depends on your sources and time range.</p>}{brief?.notice&&tab!=='saved'&&<div className="reading-note"><KeyRound size={16}/><p>{brief.notice} <button onClick={()=>setTab('settings')}>Open Settings <ArrowUpRight size={12}/></button></p></div>}<p className="coverage-note">Country coverage is prioritized, then ranked by recency, matching reports and outlet diversity. News is drawn from your selected outlets in an English-language country edition or country-focused search.</p></section>
</div></>;
 return <><a href="#main" className="skip-link">Skip to news</a><Tabs value={tab} onValueChange={v=>{setTab(String(v));if(v==='saved')api<Story[]>('saved').then(setSaved).catch(()=>setToast('Could not load saved stories'))}} className="app-shell"><header className="topbar"><a href="/" className="brand"><span className="brand-symbol"><Globe2 size={23}/></span>World Brief<span className="brand-period">.</span></a><TabsList className="main-nav"><TabsTrigger value="today"><Newspaper size={16}/><span>Today</span></TabsTrigger><TabsTrigger value="explore"><Compass size={16}/><span>Explore</span></TabsTrigger><TabsTrigger value="saved"><Bookmark size={16}/><span>Saved</span></TabsTrigger><TabsTrigger value="settings"><Settings2 size={16}/><span>Settings</span></TabsTrigger></TabsList><div className="topbar-end"><span className="local-label"><MapPin size={13}/>{country?countryName:'Personal edition'}</span><button className="icon-button" onClick={theme} aria-label={dark?'Use light appearance':'Use dark appearance'}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button></div></header>
 <main id="main" className="main-content"><TabsContent value="today">{newsSurface}</TabsContent><TabsContent value="explore">{newsSurface}</TabsContent><TabsContent value="saved">{newsSurface}</TabsContent><TabsContent value="settings"><div className="page-heading"><div><p className="eyebrow">MAKE IT YOURS</p><h1>Your country. Your sources.</h1><p className="heading-description">Choose where to focus and connect your assistant.</p></div><CountryPicker countries={countries} value={country} onChange={changeCountry} label="Settings country"/></div>
 <div className="settings-grid"><section className="settings-card"><div className="rail-card-title"><KeyRound size={20}/><h2>Connect Groq</h2></div><p className="settings-intro">Paste your API key here. It is saved in <code>.env</code> on this computer and sent only to Groq. No restart is needed.</p><form onSubmit={e=>{e.preventDefault();saveKey()}} className="key-form"><label htmlFor="groq-key">Groq API key</label><input id="groq-key" type="password" autoComplete="off" placeholder={status?.groq_configured?'A key is saved. Enter a replacement…':'gsk_…'} value={groqKey} onChange={e=>setGroqKey(e.target.value)} maxLength={300}/><div><button className="primary-button" disabled={keyBusy||!groqKey.trim()}>{keyBusy?<Loader2 className="spin" size={16}/>:<Check size={16}/>}Save & check key</button><button className="secondary-button" type="button" onClick={testKey} disabled={keyBusy||!status?.groq_configured}>Test connection</button></div></form>{keyMessage&&<p className="settings-feedback" role="status">{keyMessage}</p>}<div className="connection-row"><div><strong>Groq connection</strong><p>{status?.groq_model||'openai/gpt-oss-20b'}</p></div><span className={`connection-status ${status?.groq==='ready'?'ready':''}`}>{status?.groq.replaceAll('_',' ')||'Checking…'}</span></div><p className="small-note">Prefer editing a file? Add <code>GROQ_API_KEY=your_key</code> to <code>{status?.key_location||'.env in your project folder'}</code>. The app reads changes automatically.</p><a className="text-link" href="https://console.groq.com/keys" target="_blank" rel="noreferrer">Get a Groq API key <ArrowUpRight size={14}/></a><button className="text-link key-refresh" onClick={()=>{setTab('today');load(activeQuery,{refresh:true})}}>Refresh briefing with Groq <ChevronRight size={14}/></button></section>
 <section className="settings-card"><h2>Outlet coverage, explained.</h2><p className="settings-intro">For now, the evidence badge counts reporting outlets. No separate fact-check API key is needed.</p><div className="legend-row"><span className="evidence-badge outlet-coverage"><Newspaper size={14}/>Major outlets · Total outlets</span><p>Each distinct publisher is counted once for a matching story, even if it appears in several feeds.</p></div><div className="legend-row"><strong>Which outlets are “major”?</strong><p>A curated identity list of established national and international news brands. These outlets are labeled in your source library. Being on the list is not a truth or quality rating.</p></div><div className="legend-row"><strong>What does the count mean?</strong><p>Headline similarity and publication time suggest the outlets are reporting the same event. Syndicated reporting may appear in many outlets. The count is not independent verification.</p></div><p className="small-note">AI summaries use source headlines and available publisher RSS excerpts. Open the source reporting for full articles and context.</p></section>
 {country?<MediaSettings country={country} revision={mediaRevision} onChanged={()=>{setMediaRevision(r=>r+1);load('',{refresh:true})}}/>:<section className="settings-card"><button className="primary-button" onClick={()=>setOnboarding(true)}>Choose country to discover media</button></section>}
 <section className="settings-card"><h2>Saved on your computer.</h2><p className="settings-intro">Country and media choices, questions, summaries and source counts are stored locally.</p><div className="storage-stats"><div><strong>{status?.articles||0}</strong><span>country articles</span></div><div><strong>{status?.cached_queries||0}</strong><span>cached answers</span></div><div><strong>{saved.length}</strong><span>saved stories</span></div></div><p className="small-note">Changing country or selected outlets changes the cache key. Briefings expire after 20 minutes, and new reporting invalidates older results.</p></section></div></TabsContent><footer className="footer"><span><Globe2 size={14}/>World Brief</span><span>Stay informed. Stay curious.</span></footer></main></Tabs>
 <Dialog open={onboarding} onOpenChange={open=>{if(country)setOnboarding(open)}}><DialogContent showCloseButton={!!country} className="onboarding-dialog"><DialogHeader><span className="onboarding-icon"><Globe2 size={30}/></span><p className="eyebrow">WELCOME TO WORLD BRIEF</p><DialogTitle>Your world starts here.</DialogTitle><DialogDescription>Which country should your briefing focus on? We’ll prioritize its top stories and select up to 50 media outlets to get you started.</DialogDescription></DialogHeader><CountryPicker countries={countries} value={chosen} onChange={setChosen} label="Choose your country"/><p className="small-note">You can change your country and add or remove media outlets at any time.</p>{error&&<p role="alert" className="settings-feedback">{error}</p>}<button className="primary-button" disabled={!chosen||countryBusy} onClick={()=>changeCountry(chosen)}>{countryBusy?<Loader2 className="spin" size={17}/>:<ArrowUpRight size={17}/>}Create my briefing</button></DialogContent></Dialog>
 <Sheet open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><SheetContent className="story-sheet"><SheetHeader><SheetDescription>STORY & OUTLET COVERAGE</SheetDescription><SheetTitle>{selected?.title}</SheetTitle></SheetHeader>{selected&&<div className="sheet-body"><span className="topic-label">{selected.topic} · {ago(selected.published_at)}</span><p className="detail-summary">{selected.summary}</p><p className="small-note">{selected.summary_kind==='groq_summary'?'AI summary based on source headlines and available publisher excerpts.':'Open the linked source reporting for full articles.'}</p><button className="secondary-button" onClick={()=>bookmark(selected)}><Bookmark size={16}/>{selected.saved?'Saved to reading list':'Save for later'}</button><section className="evidence-detail"><h3>{selected.verification.major_count} major outlets reporting</h3><p>{selected.verification.total_count} distinct outlets in your selected media list.</p><div className="major-outlets">{selected.verification.major_outlets.map(o=><span key={o.id}>{o.name}</span>)}</div><p>{selected.verification.explanation}</p><p className="small-note">{selected.verification.stale?'Saved snapshot; refresh for current counts.':`Coverage counted ${ago(selected.verification.checked_at)}.`}</p></section><h3 className="sources-title">Read the reporting <span>{selected.sources.length}</span></h3>{selected.sources.map(s=><a key={s.id} href={s.url} target="_blank" rel="noreferrer" className="source-detail"><span>{s.publisher}{s.major?' · Major outlet':''}<ArrowUpRight size={15}/></span><strong>{s.title}</strong>{s.excerpt&&<p className="source-excerpt">{s.excerpt}</p>}<small>{s.link_kind==='original'?'Original publisher article · ':'News index link · '}{s.domain||'Source reporting'} · {ago(s.published_at)}</small></a>)}</div>}</SheetContent></Sheet>{toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}</>;
}
